# 워크플로의 이름 지정
name: CI

# 워크플로가 시작될 조건 지정
on:
  push:
    branches: [feat/cicd-test]

jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경 지정
    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod -x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build


# CI 테스트용 커밋