POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "pokj930@naver.com",
  "password": "1234"
}

###
GET http://localhost:8080/api/logout
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwb2tqOTMwQG5hdmVyLmNvbSIsInVzZXJJZCI6MTAsIm5hbWUiOiLthYzsiqTtirgiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIyOTQzNjM2LCJleHAiOjE3MjI5NDU0MzZ9.RQS1B3Jw24Bpd1vJFtQMq3pDOORxoyPhrN9STkLEgwM